/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.luccas.producer.model.avro;

import org.apache.avro.generic.GenericArray;
import org.apache.avro.specific.SpecificData;
import org.apache.avro.util.Utf8;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

@org.apache.avro.specific.AvroGenerated
public class AnimeMessage extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = 2924092659658605353L;


  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"AnimeMessage\",\"namespace\":\"com.luccas.producer.model.avro\",\"fields\":[{\"name\":\"name\",\"type\":[\"null\",\"string\"],\"default\":null},{\"name\":\"tipo\",\"type\":[\"null\",\"string\"],\"default\":null}],\"default\":null}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static final SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<AnimeMessage> ENCODER =
      new BinaryMessageEncoder<AnimeMessage>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<AnimeMessage> DECODER =
      new BinaryMessageDecoder<AnimeMessage>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageEncoder instance used by this class.
   * @return the message encoder used by this class
   */
  public static BinaryMessageEncoder<AnimeMessage> getEncoder() {
    return ENCODER;
  }

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   * @return the message decoder used by this class
   */
  public static BinaryMessageDecoder<AnimeMessage> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   * @return a BinaryMessageDecoder instance for this class backed by the given SchemaStore
   */
  public static BinaryMessageDecoder<AnimeMessage> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<AnimeMessage>(MODEL$, SCHEMA$, resolver);
  }

  /**
   * Serializes this AnimeMessage to a ByteBuffer.
   * @return a buffer holding the serialized data for this instance
   * @throws java.io.IOException if this instance could not be serialized
   */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /**
   * Deserializes a AnimeMessage from a ByteBuffer.
   * @param b a byte buffer holding serialized data for an instance of this class
   * @return a AnimeMessage instance decoded from the given buffer
   * @throws java.io.IOException if the given bytes could not be deserialized into an instance of this class
   */
  public static AnimeMessage fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

  private java.lang.CharSequence name;
  private java.lang.CharSequence tipo;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public AnimeMessage() {}

  /**
   * All-args constructor.
   * @param name The new value for name
   * @param tipo The new value for tipo
   */
  public AnimeMessage(java.lang.CharSequence name, java.lang.CharSequence tipo) {
    this.name = name;
    this.tipo = tipo;
  }

  public org.apache.avro.specific.SpecificData getSpecificData() { return MODEL$; }
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call.
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return name;
    case 1: return tipo;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  // Used by DatumReader.  Applications should not call.
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: name = (java.lang.CharSequence)value$; break;
    case 1: tipo = (java.lang.CharSequence)value$; break;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  /**
   * Gets the value of the 'name' field.
   * @return The value of the 'name' field.
   */
  public java.lang.CharSequence getName() {
    return name;
  }


  /**
   * Sets the value of the 'name' field.
   * @param value the value to set.
   */
  public void setName(java.lang.CharSequence value) {
    this.name = value;
  }

  /**
   * Gets the value of the 'tipo' field.
   * @return The value of the 'tipo' field.
   */
  public java.lang.CharSequence getTipo() {
    return tipo;
  }


  /**
   * Sets the value of the 'tipo' field.
   * @param value the value to set.
   */
  public void setTipo(java.lang.CharSequence value) {
    this.tipo = value;
  }

  /**
   * Creates a new AnimeMessage RecordBuilder.
   * @return A new AnimeMessage RecordBuilder
   */
  public static com.luccas.producer.model.avro.AnimeMessage.Builder newBuilder() {
    return new com.luccas.producer.model.avro.AnimeMessage.Builder();
  }

  /**
   * Creates a new AnimeMessage RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new AnimeMessage RecordBuilder
   */
  public static com.luccas.producer.model.avro.AnimeMessage.Builder newBuilder(com.luccas.producer.model.avro.AnimeMessage.Builder other) {
    if (other == null) {
      return new com.luccas.producer.model.avro.AnimeMessage.Builder();
    } else {
      return new com.luccas.producer.model.avro.AnimeMessage.Builder(other);
    }
  }

  /**
   * Creates a new AnimeMessage RecordBuilder by copying an existing AnimeMessage instance.
   * @param other The existing instance to copy.
   * @return A new AnimeMessage RecordBuilder
   */
  public static com.luccas.producer.model.avro.AnimeMessage.Builder newBuilder(com.luccas.producer.model.avro.AnimeMessage other) {
    if (other == null) {
      return new com.luccas.producer.model.avro.AnimeMessage.Builder();
    } else {
      return new com.luccas.producer.model.avro.AnimeMessage.Builder(other);
    }
  }

  /**
   * RecordBuilder for AnimeMessage instances.
   */
  @org.apache.avro.specific.AvroGenerated
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<AnimeMessage>
    implements org.apache.avro.data.RecordBuilder<AnimeMessage> {

    private java.lang.CharSequence name;
    private java.lang.CharSequence tipo;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$, MODEL$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(com.luccas.producer.model.avro.AnimeMessage.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.name)) {
        this.name = data().deepCopy(fields()[0].schema(), other.name);
        fieldSetFlags()[0] = other.fieldSetFlags()[0];
      }
      if (isValidValue(fields()[1], other.tipo)) {
        this.tipo = data().deepCopy(fields()[1].schema(), other.tipo);
        fieldSetFlags()[1] = other.fieldSetFlags()[1];
      }
    }

    /**
     * Creates a Builder by copying an existing AnimeMessage instance
     * @param other The existing instance to copy.
     */
    private Builder(com.luccas.producer.model.avro.AnimeMessage other) {
      super(SCHEMA$, MODEL$);
      if (isValidValue(fields()[0], other.name)) {
        this.name = data().deepCopy(fields()[0].schema(), other.name);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.tipo)) {
        this.tipo = data().deepCopy(fields()[1].schema(), other.tipo);
        fieldSetFlags()[1] = true;
      }
    }

    /**
      * Gets the value of the 'name' field.
      * @return The value.
      */
    public java.lang.CharSequence getName() {
      return name;
    }


    /**
      * Sets the value of the 'name' field.
      * @param value The value of 'name'.
      * @return This builder.
      */
    public com.luccas.producer.model.avro.AnimeMessage.Builder setName(java.lang.CharSequence value) {
      validate(fields()[0], value);
      this.name = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'name' field has been set.
      * @return True if the 'name' field has been set, false otherwise.
      */
    public boolean hasName() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'name' field.
      * @return This builder.
      */
    public com.luccas.producer.model.avro.AnimeMessage.Builder clearName() {
      name = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'tipo' field.
      * @return The value.
      */
    public java.lang.CharSequence getTipo() {
      return tipo;
    }


    /**
      * Sets the value of the 'tipo' field.
      * @param value The value of 'tipo'.
      * @return This builder.
      */
    public com.luccas.producer.model.avro.AnimeMessage.Builder setTipo(java.lang.CharSequence value) {
      validate(fields()[1], value);
      this.tipo = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'tipo' field has been set.
      * @return True if the 'tipo' field has been set, false otherwise.
      */
    public boolean hasTipo() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'tipo' field.
      * @return This builder.
      */
    public com.luccas.producer.model.avro.AnimeMessage.Builder clearTipo() {
      tipo = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public AnimeMessage build() {
      try {
        AnimeMessage record = new AnimeMessage();
        record.name = fieldSetFlags()[0] ? this.name : (java.lang.CharSequence) defaultValue(fields()[0]);
        record.tipo = fieldSetFlags()[1] ? this.tipo : (java.lang.CharSequence) defaultValue(fields()[1]);
        return record;
      } catch (org.apache.avro.AvroMissingFieldException e) {
        throw e;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<AnimeMessage>
    WRITER$ = (org.apache.avro.io.DatumWriter<AnimeMessage>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<AnimeMessage>
    READER$ = (org.apache.avro.io.DatumReader<AnimeMessage>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

  @Override protected boolean hasCustomCoders() { return true; }

  @Override public void customEncode(org.apache.avro.io.Encoder out)
    throws java.io.IOException
  {
    if (this.name == null) {
      out.writeIndex(0);
      out.writeNull();
    } else {
      out.writeIndex(1);
      out.writeString(this.name);
    }

    if (this.tipo == null) {
      out.writeIndex(0);
      out.writeNull();
    } else {
      out.writeIndex(1);
      out.writeString(this.tipo);
    }

  }

  @Override public void customDecode(org.apache.avro.io.ResolvingDecoder in)
    throws java.io.IOException
  {
    org.apache.avro.Schema.Field[] fieldOrder = in.readFieldOrderIfDiff();
    if (fieldOrder == null) {
      if (in.readIndex() != 1) {
        in.readNull();
        this.name = null;
      } else {
        this.name = in.readString(this.name instanceof Utf8 ? (Utf8)this.name : null);
      }

      if (in.readIndex() != 1) {
        in.readNull();
        this.tipo = null;
      } else {
        this.tipo = in.readString(this.tipo instanceof Utf8 ? (Utf8)this.tipo : null);
      }

    } else {
      for (int i = 0; i < 2; i++) {
        switch (fieldOrder[i].pos()) {
        case 0:
          if (in.readIndex() != 1) {
            in.readNull();
            this.name = null;
          } else {
            this.name = in.readString(this.name instanceof Utf8 ? (Utf8)this.name : null);
          }
          break;

        case 1:
          if (in.readIndex() != 1) {
            in.readNull();
            this.tipo = null;
          } else {
            this.tipo = in.readString(this.tipo instanceof Utf8 ? (Utf8)this.tipo : null);
          }
          break;

        default:
          throw new java.io.IOException("Corrupt ResolvingDecoder.");
        }
      }
    }
  }
}










