/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.luccas.producer.model.avro;

@org.apache.avro.specific.AvroGenerated
public interface ProtocolMessaage {
  public static final org.apache.avro.Protocol PROTOCOL = org.apache.avro.Protocol.parse("{\"protocol\":\"ProtocolMessaage\",\"namespace\":\"com.luccas.producer.model.avro\",\"types\":[{\"type\":\"record\",\"name\":\"AnimeMessage\",\"fields\":[{\"name\":\"name\",\"type\":[\"null\",\"string\"],\"default\":null},{\"name\":\"tipo\",\"type\":[\"null\",\"string\"],\"default\":null}],\"default\":null},{\"type\":\"record\",\"name\":\"CatalogAnimesMessage\",\"fields\":[{\"name\":\"id\",\"type\":[\"null\",\"string\"],\"default\":null},{\"name\":\"animesList\",\"type\":[\"null\",{\"type\":\"array\",\"items\":\"AnimeMessage\",\"class\":\"java.util.List\"}],\"default\":null}]}],\"messages\":{}}");

  @org.apache.avro.specific.AvroGenerated
  public interface Callback extends ProtocolMessaage {
    public static final org.apache.avro.Protocol PROTOCOL = com.luccas.producer.model.avro.ProtocolMessaage.PROTOCOL;
  }
}